// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: csv_uploads.sql

package db

import (
	"context"
)

const getCsvUpload = `-- name: GetCsvUpload :many
SELECT name, action, uploaded_at
FROM csv_uploads
WHERE name = $1
`

func (q *Queries) GetCsvUpload(ctx context.Context, name string) ([]CsvUpload, error) {
	rows, err := q.db.Query(ctx, getCsvUpload, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsvUpload{}
	for rows.Next() {
		var i CsvUpload
		if err := rows.Scan(&i.Name, &i.Action, &i.UploadedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCsvUpload = `-- name: InsertCsvUpload :exec
INSERT INTO csv_uploads (name, action, uploaded_at)
VALUES ($1, $2, NOW())
ON CONFLICT (name, action) DO NOTHING
`

type InsertCsvUploadParams struct {
	Name   string `json:"name"`
	Action string `json:"action"`
}

func (q *Queries) InsertCsvUpload(ctx context.Context, arg InsertCsvUploadParams) error {
	_, err := q.db.Exec(ctx, insertCsvUpload, arg.Name, arg.Action)
	return err
}

const resetCsvUploads = `-- name: ResetCsvUploads :exec
DELETE FROM csv_uploads
`

func (q *Queries) ResetCsvUploads(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetCsvUploads)
	return err
}
