// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnrokTransaction struct {
	ID                        pgtype.UUID    `json:"id"`
	TransactionID             pgtype.Text    `json:"transaction_id"`
	CustomerID                pgtype.Text    `json:"customer_id"`
	CustomerName              pgtype.Text    `json:"customer_name"`
	OverallVatIDStatus        pgtype.Text    `json:"overall_vat_id_status"`
	ValidVatIds               pgtype.Text    `json:"valid_vat_ids"`
	OtherVatIds               pgtype.Text    `json:"other_vat_ids"`
	InvoiceDate               pgtype.Date    `json:"invoice_date"`
	TaxDate                   pgtype.Date    `json:"tax_date"`
	TransactionCurrency       pgtype.Text    `json:"transaction_currency"`
	SalesAmount               pgtype.Numeric `json:"sales_amount"`
	ExemptReason              pgtype.Text    `json:"exempt_reason"`
	TaxAmount                 pgtype.Numeric `json:"tax_amount"`
	InvoiceAmount             pgtype.Numeric `json:"invoice_amount"`
	Void                      pgtype.Bool    `json:"void"`
	CustomerAddressLine1      pgtype.Text    `json:"customer_address_line_1"`
	CustomerAddressCity       pgtype.Text    `json:"customer_address_city"`
	CustomerAddressRegion     pgtype.Text    `json:"customer_address_region"`
	CustomerAddressPostalCode pgtype.Text    `json:"customer_address_postal_code"`
	CustomerAddressCountry    pgtype.Text    `json:"customer_address_country"`
	CustomerCountryCode       pgtype.Text    `json:"customer_country_code"`
	Jurisdictions             pgtype.Text    `json:"jurisdictions"`
	JurisdictionIds           pgtype.Text    `json:"jurisdiction_ids"`
	ReturnIds                 pgtype.Text    `json:"return_ids"`
	UploadID                  pgtype.UUID    `json:"upload_id"`
}

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	Action         string             `json:"action"`
	Severity       string             `json:"severity"`
	TableKey       string             `json:"table_key"`
	UserID         pgtype.Text        `json:"user_id"`
	UserEmail      pgtype.Text        `json:"user_email"`
	UserName       pgtype.Text        `json:"user_name"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	RowKey         pgtype.Text        `json:"row_key"`
	ColumnName     pgtype.Text        `json:"column_name"`
	OldValue       pgtype.Text        `json:"old_value"`
	NewValue       pgtype.Text        `json:"new_value"`
	RowData        []byte             `json:"row_data"`
	RowsAffected   pgtype.Int4        `json:"rows_affected"`
	UploadID       pgtype.UUID        `json:"upload_id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	RelatedAuditID pgtype.UUID        `json:"related_audit_id"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuditLogArchive struct {
	ID             pgtype.UUID        `json:"id"`
	Action         string             `json:"action"`
	Severity       string             `json:"severity"`
	TableKey       string             `json:"table_key"`
	UserID         pgtype.Text        `json:"user_id"`
	UserEmail      pgtype.Text        `json:"user_email"`
	UserName       pgtype.Text        `json:"user_name"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	RowKey         pgtype.Text        `json:"row_key"`
	ColumnName     pgtype.Text        `json:"column_name"`
	OldValue       pgtype.Text        `json:"old_value"`
	NewValue       pgtype.Text        `json:"new_value"`
	RowData        []byte             `json:"row_data"`
	RowsAffected   pgtype.Int4        `json:"rows_affected"`
	UploadID       pgtype.UUID        `json:"upload_id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	RelatedAuditID pgtype.UUID        `json:"related_audit_id"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
}

type CsvUpload struct {
	Name         string           `json:"name"`
	Action       string           `json:"action"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	ID           pgtype.UUID      `json:"id"`
	FileName     pgtype.Text      `json:"file_name"`
	RowsInserted pgtype.Int4      `json:"rows_inserted"`
	RowsSkipped  pgtype.Int4      `json:"rows_skipped"`
	DurationMs   pgtype.Int4      `json:"duration_ms"`
	Status       pgtype.Text      `json:"status"`
	CsvHeaders   []string         `json:"csv_headers"`
}

type ImportTemplate struct {
	ID            pgtype.UUID      `json:"id"`
	TableKey      string           `json:"table_key"`
	Name          string           `json:"name"`
	ColumnMapping []byte           `json:"column_mapping"`
	CsvHeaders    []byte           `json:"csv_headers"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type NsCustomer struct {
	ID             pgtype.UUID    `json:"id"`
	SalesforceIDIo pgtype.Text    `json:"salesforce_id_io"`
	InternalID     pgtype.Text    `json:"internal_id"`
	Name           pgtype.Text    `json:"name"`
	Duplicate      pgtype.Text    `json:"duplicate"`
	CompanyName    pgtype.Text    `json:"company_name"`
	Balance        pgtype.Numeric `json:"balance"`
	UnbilledOrders pgtype.Numeric `json:"unbilled_orders"`
	OverdueBalance pgtype.Numeric `json:"overdue_balance"`
	DaysOverdue    pgtype.Numeric `json:"days_overdue"`
	UploadID       pgtype.UUID    `json:"upload_id"`
}

type NsInvoiceDetail struct {
	ID                     pgtype.UUID    `json:"id"`
	SfdcOppID              pgtype.Text    `json:"sfdc_opp_id"`
	SfdcOppLineID          pgtype.Text    `json:"sfdc_opp_line_id"`
	SfdcPricebookID        pgtype.Text    `json:"sfdc_pricebook_id"`
	CustomerInternalID     pgtype.Text    `json:"customer_internal_id"`
	ProductInternalID      pgtype.Text    `json:"product_internal_id"`
	Type                   pgtype.Text    `json:"type"`
	Date                   pgtype.Date    `json:"date"`
	DateDue                pgtype.Date    `json:"date_due"`
	DocumentNumber         pgtype.Text    `json:"document_number"`
	Name                   pgtype.Text    `json:"name"`
	Memo                   pgtype.Text    `json:"memo"`
	Item                   pgtype.Text    `json:"item"`
	Qty                    pgtype.Numeric `json:"qty"`
	ContractQuantity       pgtype.Numeric `json:"contract_quantity"`
	UnitPrice              pgtype.Numeric `json:"unit_price"`
	Amount                 pgtype.Numeric `json:"amount"`
	StartDateLine          pgtype.Date    `json:"start_date_line"`
	EndDateLineLevel       pgtype.Date    `json:"end_date_line_level"`
	Account                pgtype.Text    `json:"account"`
	ShippingAddressCity    pgtype.Text    `json:"shipping_address_city"`
	ShippingAddressState   pgtype.Text    `json:"shipping_address_state"`
	ShippingAddressCountry pgtype.Text    `json:"shipping_address_country"`
	UploadID               pgtype.UUID    `json:"upload_id"`
}

type NsSoDetail struct {
	ID                  pgtype.UUID    `json:"id"`
	SfdcOppID           pgtype.Text    `json:"sfdc_opp_id"`
	SfdcOppLineID       pgtype.Text    `json:"sfdc_opp_line_id"`
	CustomerInternalID  pgtype.Text    `json:"customer_internal_id"`
	ProductInternalID   pgtype.Text    `json:"product_internal_id"`
	CustomerProject     string         `json:"customer_project"`
	SoNumber            pgtype.Text    `json:"so_number"`
	DocumentDate        pgtype.Date    `json:"document_date"`
	StartDate           pgtype.Date    `json:"start_date"`
	EndDate             pgtype.Date    `json:"end_date"`
	ItemName            pgtype.Text    `json:"item_name"`
	ItemDisplayName     pgtype.Text    `json:"item_display_name"`
	LineStartDate       pgtype.Date    `json:"line_start_date"`
	LineEndDate         pgtype.Date    `json:"line_end_date"`
	Quantity            pgtype.Numeric `json:"quantity"`
	UnitPrice           pgtype.Numeric `json:"unit_price"`
	AmountGross         pgtype.Numeric `json:"amount_gross"`
	TermsDaysTillNetDue pgtype.Numeric `json:"terms_days_till_net_due"`
	UploadID            pgtype.UUID    `json:"upload_id"`
}

type SfdcCustomer struct {
	ID                pgtype.UUID `json:"id"`
	AccountIDCasesafe pgtype.Text `json:"account_id_casesafe"`
	AccountName       pgtype.Text `json:"account_name"`
	LastActivity      pgtype.Date `json:"last_activity"`
	Type              pgtype.Text `json:"type"`
	UploadID          pgtype.UUID `json:"upload_id"`
}

type SfdcOppDetail struct {
	ID                           pgtype.UUID    `json:"id"`
	OpportunityID                pgtype.Text    `json:"opportunity_id"`
	OpportunityProductCasesafeID pgtype.Text    `json:"opportunity_product_casesafe_id"`
	OpportunityName              pgtype.Text    `json:"opportunity_name"`
	AccountName                  pgtype.Text    `json:"account_name"`
	CloseDate                    pgtype.Date    `json:"close_date"`
	BookedDate                   pgtype.Date    `json:"booked_date"`
	FiscalPeriod                 pgtype.Text    `json:"fiscal_period"`
	PaymentSchedule              pgtype.Text    `json:"payment_schedule"`
	PaymentDue                   pgtype.Text    `json:"payment_due"`
	ContractStartDate            pgtype.Date    `json:"contract_start_date"`
	ContractEndDate              pgtype.Date    `json:"contract_end_date"`
	TermInMonthsDeprecated       pgtype.Numeric `json:"term_in_months_deprecated"`
	ProductName                  pgtype.Text    `json:"product_name"`
	DeploymentType               pgtype.Text    `json:"deployment_type"`
	Amount                       pgtype.Numeric `json:"amount"`
	Quantity                     pgtype.Numeric `json:"quantity"`
	ListPrice                    pgtype.Numeric `json:"list_price"`
	SalesPrice                   pgtype.Numeric `json:"sales_price"`
	TotalPrice                   pgtype.Numeric `json:"total_price"`
	StartDate                    pgtype.Date    `json:"start_date"`
	EndDate                      pgtype.Date    `json:"end_date"`
	TermInMonths                 pgtype.Numeric `json:"term_in_months"`
	ProductCode                  pgtype.Text    `json:"product_code"`
	TotalAmountDueCustomer       pgtype.Numeric `json:"total_amount_due_customer"`
	TotalAmountDuePartner        pgtype.Numeric `json:"total_amount_due_partner"`
	ActiveProduct                pgtype.Bool    `json:"active_product"`
	UploadID                     pgtype.UUID    `json:"upload_id"`
}

type SfdcPriceBook struct {
	ID                pgtype.UUID    `json:"id"`
	PriceBookName     pgtype.Text    `json:"price_book_name"`
	ListPrice         pgtype.Numeric `json:"list_price"`
	ProductName       pgtype.Text    `json:"product_name"`
	ProductCode       pgtype.Text    `json:"product_code"`
	ProductIDCasesafe pgtype.Text    `json:"product_id_casesafe"`
	UploadID          pgtype.UUID    `json:"upload_id"`
}

type UploadFailedRow struct {
	ID         pgtype.UUID        `json:"id"`
	UploadID   pgtype.UUID        `json:"upload_id"`
	LineNumber int32              `json:"line_number"`
	Reason     string             `json:"reason"`
	RowData    []string           `json:"row_data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
