// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ns_customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNsCustomer = `-- name: InsertNsCustomer :exec
INSERT INTO ns_customers (
    salesforce_id_io,
    internal_id,
    name,
    duplicate,
    company_name,
    balance,
    unbilled_orders,
    overdue_balance,
    days_overdue
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertNsCustomerParams struct {
	SalesforceIDIo pgtype.Text    `json:"salesforce_id_io"`
	InternalID     pgtype.Text    `json:"internal_id"`
	Name           pgtype.Text    `json:"name"`
	Duplicate      pgtype.Text    `json:"duplicate"`
	CompanyName    pgtype.Text    `json:"company_name"`
	Balance        pgtype.Numeric `json:"balance"`
	UnbilledOrders pgtype.Numeric `json:"unbilled_orders"`
	OverdueBalance pgtype.Numeric `json:"overdue_balance"`
	DaysOverdue    pgtype.Numeric `json:"days_overdue"`
}

func (q *Queries) InsertNsCustomer(ctx context.Context, arg InsertNsCustomerParams) error {
	_, err := q.db.Exec(ctx, insertNsCustomer,
		arg.SalesforceIDIo,
		arg.InternalID,
		arg.Name,
		arg.Duplicate,
		arg.CompanyName,
		arg.Balance,
		arg.UnbilledOrders,
		arg.OverdueBalance,
		arg.DaysOverdue,
	)
	return err
}

const resetNsCustomers = `-- name: ResetNsCustomers :exec
DELETE FROM ns_customers
`

func (q *Queries) ResetNsCustomers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetNsCustomers)
	return err
}
