// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ns_customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNsCustomers = `-- name: CountNsCustomers :one
SELECT COUNT(*) FROM ns_customers
`

func (q *Queries) CountNsCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNsCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNsCustomersByUploadId = `-- name: DeleteNsCustomersByUploadId :execrows
DELETE FROM ns_customers WHERE upload_id = $1
`

func (q *Queries) DeleteNsCustomersByUploadId(ctx context.Context, uploadID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNsCustomersByUploadId, uploadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNsCustomer = `-- name: InsertNsCustomer :exec
INSERT INTO ns_customers (
    salesforce_id_io,
    internal_id,
    name,
    duplicate,
    company_name,
    balance,
    unbilled_orders,
    overdue_balance,
    days_overdue,
    upload_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertNsCustomerParams struct {
	SalesforceIDIo pgtype.Text    `json:"salesforce_id_io"`
	InternalID     pgtype.Text    `json:"internal_id"`
	Name           pgtype.Text    `json:"name"`
	Duplicate      pgtype.Text    `json:"duplicate"`
	CompanyName    pgtype.Text    `json:"company_name"`
	Balance        pgtype.Numeric `json:"balance"`
	UnbilledOrders pgtype.Numeric `json:"unbilled_orders"`
	OverdueBalance pgtype.Numeric `json:"overdue_balance"`
	DaysOverdue    pgtype.Numeric `json:"days_overdue"`
	UploadID       pgtype.UUID    `json:"upload_id"`
}

func (q *Queries) InsertNsCustomer(ctx context.Context, arg InsertNsCustomerParams) error {
	_, err := q.db.Exec(ctx, insertNsCustomer,
		arg.SalesforceIDIo,
		arg.InternalID,
		arg.Name,
		arg.Duplicate,
		arg.CompanyName,
		arg.Balance,
		arg.UnbilledOrders,
		arg.OverdueBalance,
		arg.DaysOverdue,
		arg.UploadID,
	)
	return err
}

const resetNsCustomers = `-- name: ResetNsCustomers :exec
DELETE FROM ns_customers
`

func (q *Queries) ResetNsCustomers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetNsCustomers)
	return err
}
