// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ns_invoice_detail.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNsInvoiceDetail = `-- name: InsertNsInvoiceDetail :exec
INSERT INTO ns_invoice_detail (
    sfdc_opp_id,
    sfdc_opp_line_id,
    sfdc_pricebook_id,
    customer_internal_id,
    product_internal_id,
    type,
    date,
    date_due,
    document_number,
    name,
    memo,
    item,
    qty,
    contract_quantity,
    unit_price,
    amount,
    start_date_line,
    end_date_line_level,
    account,
    shipping_address_city,
    shipping_address_state,
    shipping_address_country
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
`

type InsertNsInvoiceDetailParams struct {
	SfdcOppID              pgtype.Text    `json:"sfdc_opp_id"`
	SfdcOppLineID          pgtype.Text    `json:"sfdc_opp_line_id"`
	SfdcPricebookID        pgtype.Text    `json:"sfdc_pricebook_id"`
	CustomerInternalID     pgtype.Text    `json:"customer_internal_id"`
	ProductInternalID      pgtype.Text    `json:"product_internal_id"`
	Type                   pgtype.Text    `json:"type"`
	Date                   pgtype.Date    `json:"date"`
	DateDue                pgtype.Date    `json:"date_due"`
	DocumentNumber         pgtype.Text    `json:"document_number"`
	Name                   pgtype.Text    `json:"name"`
	Memo                   pgtype.Text    `json:"memo"`
	Item                   pgtype.Text    `json:"item"`
	Qty                    pgtype.Numeric `json:"qty"`
	ContractQuantity       pgtype.Numeric `json:"contract_quantity"`
	UnitPrice              pgtype.Numeric `json:"unit_price"`
	Amount                 pgtype.Numeric `json:"amount"`
	StartDateLine          pgtype.Date    `json:"start_date_line"`
	EndDateLineLevel       pgtype.Date    `json:"end_date_line_level"`
	Account                pgtype.Text    `json:"account"`
	ShippingAddressCity    pgtype.Text    `json:"shipping_address_city"`
	ShippingAddressState   pgtype.Text    `json:"shipping_address_state"`
	ShippingAddressCountry pgtype.Text    `json:"shipping_address_country"`
}

func (q *Queries) InsertNsInvoiceDetail(ctx context.Context, arg InsertNsInvoiceDetailParams) error {
	_, err := q.db.Exec(ctx, insertNsInvoiceDetail,
		arg.SfdcOppID,
		arg.SfdcOppLineID,
		arg.SfdcPricebookID,
		arg.CustomerInternalID,
		arg.ProductInternalID,
		arg.Type,
		arg.Date,
		arg.DateDue,
		arg.DocumentNumber,
		arg.Name,
		arg.Memo,
		arg.Item,
		arg.Qty,
		arg.ContractQuantity,
		arg.UnitPrice,
		arg.Amount,
		arg.StartDateLine,
		arg.EndDateLineLevel,
		arg.Account,
		arg.ShippingAddressCity,
		arg.ShippingAddressState,
		arg.ShippingAddressCountry,
	)
	return err
}

const resetNsInvoiceDetail = `-- name: ResetNsInvoiceDetail :exec
DELETE FROM ns_invoice_detail
`

func (q *Queries) ResetNsInvoiceDetail(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetNsInvoiceDetail)
	return err
}
