// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sfdc_opp_detail.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSfdcOppDetail = `-- name: InsertSfdcOppDetail :exec
INSERT INTO sfdc_opp_detail (
    opportunity_id,
    opportunity_product_casesafe_id,
    opportunity_name,
    account_name,
    close_date,
    booked_date,
    fiscal_period,
    payment_schedule,
    payment_due,
    contract_start_date,
    contract_end_date,
    term_in_months_deprecated,
    product_name,
    deployment_type,
    amount,
    quantity,
    list_price,
    sales_price,
    total_price,
    start_date,
    end_date,
    term_in_months,
    product_code,
    total_amount_due_customer,
    total_amount_due_partner,
    active_product
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
`

type InsertSfdcOppDetailParams struct {
	OpportunityID                pgtype.Text    `json:"opportunity_id"`
	OpportunityProductCasesafeID pgtype.Text    `json:"opportunity_product_casesafe_id"`
	OpportunityName              pgtype.Text    `json:"opportunity_name"`
	AccountName                  pgtype.Text    `json:"account_name"`
	CloseDate                    pgtype.Date    `json:"close_date"`
	BookedDate                   pgtype.Date    `json:"booked_date"`
	FiscalPeriod                 pgtype.Text    `json:"fiscal_period"`
	PaymentSchedule              pgtype.Text    `json:"payment_schedule"`
	PaymentDue                   pgtype.Text    `json:"payment_due"`
	ContractStartDate            pgtype.Date    `json:"contract_start_date"`
	ContractEndDate              pgtype.Date    `json:"contract_end_date"`
	TermInMonthsDeprecated       pgtype.Numeric `json:"term_in_months_deprecated"`
	ProductName                  pgtype.Text    `json:"product_name"`
	DeploymentType               pgtype.Text    `json:"deployment_type"`
	Amount                       pgtype.Numeric `json:"amount"`
	Quantity                     pgtype.Numeric `json:"quantity"`
	ListPrice                    pgtype.Numeric `json:"list_price"`
	SalesPrice                   pgtype.Numeric `json:"sales_price"`
	TotalPrice                   pgtype.Numeric `json:"total_price"`
	StartDate                    pgtype.Date    `json:"start_date"`
	EndDate                      pgtype.Date    `json:"end_date"`
	TermInMonths                 pgtype.Numeric `json:"term_in_months"`
	ProductCode                  pgtype.Text    `json:"product_code"`
	TotalAmountDueCustomer       pgtype.Numeric `json:"total_amount_due_customer"`
	TotalAmountDuePartner        pgtype.Numeric `json:"total_amount_due_partner"`
	ActiveProduct                pgtype.Bool    `json:"active_product"`
}

func (q *Queries) InsertSfdcOppDetail(ctx context.Context, arg InsertSfdcOppDetailParams) error {
	_, err := q.db.Exec(ctx, insertSfdcOppDetail,
		arg.OpportunityID,
		arg.OpportunityProductCasesafeID,
		arg.OpportunityName,
		arg.AccountName,
		arg.CloseDate,
		arg.BookedDate,
		arg.FiscalPeriod,
		arg.PaymentSchedule,
		arg.PaymentDue,
		arg.ContractStartDate,
		arg.ContractEndDate,
		arg.TermInMonthsDeprecated,
		arg.ProductName,
		arg.DeploymentType,
		arg.Amount,
		arg.Quantity,
		arg.ListPrice,
		arg.SalesPrice,
		arg.TotalPrice,
		arg.StartDate,
		arg.EndDate,
		arg.TermInMonths,
		arg.ProductCode,
		arg.TotalAmountDueCustomer,
		arg.TotalAmountDuePartner,
		arg.ActiveProduct,
	)
	return err
}

const resetSfdcOppDetail = `-- name: ResetSfdcOppDetail :exec
DELETE FROM sfdc_opp_detail
`

func (q *Queries) ResetSfdcOppDetail(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetSfdcOppDetail)
	return err
}
