// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sfdc_customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSfdcCustomers = `-- name: CountSfdcCustomers :one
SELECT COUNT(*) FROM sfdc_customers
`

func (q *Queries) CountSfdcCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSfdcCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSfdcCustomer = `-- name: InsertSfdcCustomer :exec
INSERT INTO sfdc_customers (
    account_id_casesafe,
    account_name,
    last_activity,
    type
)
VALUES ($1, $2, $3, $4)
`

type InsertSfdcCustomerParams struct {
	AccountIDCasesafe pgtype.Text `json:"account_id_casesafe"`
	AccountName       pgtype.Text `json:"account_name"`
	LastActivity      pgtype.Date `json:"last_activity"`
	Type              pgtype.Text `json:"type"`
}

func (q *Queries) InsertSfdcCustomer(ctx context.Context, arg InsertSfdcCustomerParams) error {
	_, err := q.db.Exec(ctx, insertSfdcCustomer,
		arg.AccountIDCasesafe,
		arg.AccountName,
		arg.LastActivity,
		arg.Type,
	)
	return err
}

const resetSfdcCustomers = `-- name: ResetSfdcCustomers :exec
DELETE FROM sfdc_customers
`

func (q *Queries) ResetSfdcCustomers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetSfdcCustomers)
	return err
}
